// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuj4xOpvV8GL7ZaSSLaoiZZAVmd8KMlYY',
    appId: '1:770532769502:web:9f288d4d4a644a6ca50c4f',
    messagingSenderId: '770532769502',
    projectId: 'aval-flutter',
    authDomain: 'aval-flutter.firebaseapp.com',
    storageBucket: 'aval-flutter.firebasestorage.app',
    measurementId: 'G-2KXH35RSW5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdTL9Bf-esZqnytbMzB3fiBwSMNXcjclk',
    appId: '1:770532769502:android:a416f9c1510a86e8a50c4f',
    messagingSenderId: '770532769502',
    projectId: 'aval-flutter',
    storageBucket: 'aval-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtyNIarKpoCTL3Odyr34n6PN_FUC25_XY',
    appId: '1:770532769502:ios:4f54a094a6db3d8ca50c4f',
    messagingSenderId: '770532769502',
    projectId: 'aval-flutter',
    storageBucket: 'aval-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterAval',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtyNIarKpoCTL3Odyr34n6PN_FUC25_XY',
    appId: '1:770532769502:ios:4f54a094a6db3d8ca50c4f',
    messagingSenderId: '770532769502',
    projectId: 'aval-flutter',
    storageBucket: 'aval-flutter.firebasestorage.app',
    iosBundleId: 'com.example.flutterAval',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuj4xOpvV8GL7ZaSSLaoiZZAVmd8KMlYY',
    appId: '1:770532769502:web:35204b5b1a5d9cb2a50c4f',
    messagingSenderId: '770532769502',
    projectId: 'aval-flutter',
    authDomain: 'aval-flutter.firebaseapp.com',
    storageBucket: 'aval-flutter.firebasestorage.app',
    measurementId: 'G-0Z26XXSDCW',
  );

}